name: douban_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.6
  flutter_webview_plugin: ^0.3.10+1
  fluttertoast: ^3.1.3
  dio: ^3.0.8
  video_player: ^0.10.5+1
  pull_to_refresh: ^1.5.8
  photo_view: ^0.9.1
  flutter_swiper : ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # assets-generator-begin
    # assets/images/*
    - assets/images/.DS_Store
    - assets/images/bg_books_stack_default.png
    - assets/images/bg_music_stack_default.png
    - assets/images/bg_person_center_default.webp
    - assets/images/bg_videos_stack_default.png
    - assets/images/douban_film_list.png
    - assets/images/douban_guess.png
    - assets/images/douban_top.png
    - assets/images/find_movie.png
    - assets/images/home.png
    - assets/images/ic_action_playable_video_s.png
    - assets/images/ic_arrow_back.png
    - assets/images/ic_circle_yellow.png
    - assets/images/ic_default_img_subject_movie.png
    - assets/images/ic_group_check_anonymous.png
    - assets/images/ic_group_checked_anonymous.png
    - assets/images/ic_group_top.png
    - assets/images/ic_info_done.png
    - assets/images/ic_info_wish.png
    - assets/images/ic_launcher.png
    - assets/images/ic_me_doulist.png
    - assets/images/ic_me_follows.png
    - assets/images/ic_me_journal.png
    - assets/images/ic_me_photo_album.png
    - assets/images/ic_me_wallet.png
    - assets/images/ic_more.png
    - assets/images/ic_new_empty_view_default.png
    - assets/images/ic_notification_tv_calendar_comments.png
    - assets/images/ic_notify.png
    - assets/images/ic_pause.png
    - assets/images/ic_playing.png
    - assets/images/ic_status_detail_reshare_icon.png
    - assets/images/ic_subject_mark_added.png
    - assets/images/ic_subject_rating_mark_wish.png
    - assets/images/ic_tab_group_active.png
    - assets/images/ic_tab_group_normal.png
    - assets/images/ic_tab_home_active.png
    - assets/images/ic_tab_home_normal.png
    - assets/images/ic_tab_profile_active.png
    - assets/images/ic_tab_profile_normal.png
    - assets/images/ic_tab_shiji_active.png
    - assets/images/ic_tab_shiji_normal.png
    - assets/images/ic_tab_subject_active.png
    - assets/images/ic_tab_subject_normal.png
    - assets/images/ic_vote.png
    - assets/images/ic_vote_normal_large.png
    - assets/images/landscape.png
    - assets/images/person_top_bg.jpg
    - assets/images/scanning.png
    - assets/images/sofa.png
    # assets-generator-end
    - mock/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
